# Generated by Django 2.2.2 on 2019-07-19 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APP01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='cls',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='APP01.classes'),
            preserve_default=False,
        ),
    ]
